spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
pl:
  fc:
    invoicing:
      db:
        mode: jpa