package com.fc.invoicing.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.UUID;
import javax.persistence.Column;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class CompanyListDto {

    @Schema(name = "Company id (generated by application)", required = true, example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    private UUID companyId;
    @Schema(name = "taxIdentificationNumber", example = "5556677888", required = true)
    private String taxIdentificationNumber;
    @Schema(name = "name", example = "Creative", required = true)
    private String name;
}
