package com.fc.invoicing.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CompanyDto {

    @Schema(name = "Company id (generated by application)", required = true, example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    private UUID companyId;
    @Schema(name = "taxIdentificationNumber", example = "5556677888", required = true)
    private String taxIdentificationNumber;
    @Schema(name = "name", example = "Creative", required = true)
    private String name;
    @Schema(name = "address", example = "ul.Buraczana 13/5, 17-666, Szczecin", required = true)
    private String address;
    @Schema(name = "healthInsurance", example = "123.45", required = true)
    private BigDecimal healthInsurance;
    @Schema(name = "pensionInsurance", example = "234.47", required = true)
    private BigDecimal pensionInsurance;
}
