package com.fc.invoicing.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name = "companies")
public class Company {

    @Id
    @JsonIgnore
    @GeneratedValue
    @Schema(name = "Company id (generated by application)", required = true, example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    private UUID companyId;
    @Column(name = "tax_identification_number")
    @Schema(name = "taxIdentificationNumber", example = "5556677888", required = true)
    private String taxIdentificationNumber;
    @Schema(name = "name", example = "Creative", required = true)
    private String name;
    @Schema(name = "address", example = "ul.Buraczana 13/5, 17-666, Szczecin", required = true)
    private String address;
    @Column(name = "healthy_insurance")
    @Schema(name = "healthInsurance", example = "123.45", required = true)
    private BigDecimal healthInsurance;
    @Column(name = "pension_insurance")
    @Schema(name = "pensionInsurance", example = "234.47", required = true)
    private BigDecimal pensionInsurance;

    public Company(String taxIdentificationNumber, String name, String address, BigDecimal healthInsurance, BigDecimal pensionInsurance) {
        this.taxIdentificationNumber = taxIdentificationNumber;
        this.name = name;
        this.address = address;
        this.healthInsurance = healthInsurance;
        this.pensionInsurance = pensionInsurance;
    }
}
